### ISSUE TITLE
Another install error?

### ISSUE THREAD

**Issue by ogamimusashi** [arrayfire/arrayfire_r#4]
Hello,
I'm trying to install arrayfire_r, doing 
sudo R CMD INSTALL arrayfire_r-master

I'm getting the following error, which seems a bit different from the other one reported:

* installing to library ‘/home/ogami/R/x86_64-pc-linux-gnu-library/3.0’
* installing *source* package ‘arrayfire’ ...
** libs
g++ -I/usr/share/R/include -DNDEBUG -I/usr/local/cuda-6.5//include -I/usr/local/cuda-6.5/bin/arrayfire/include     -fpic  -O3 -pipe  -g  -c R_wrapper.cpp -o R_wrapper.o
In file included from R_wrapper.cpp:2:0:
R_wrapper.h:8:22: fatal error: af/utils.h: No such file or directory
 #include <af/utils.h>
                      ^
compilation terminated.
make: *** [R_wrapper.o] Error 1
ERROR: compilation failed for package ‘arrayfire’

Could you please help me? Thank you!

**Comment by pavanky** [comment]
@ogamimusashi The current version of the R wrapper requires ArrayFire 2.1 which is not open source. The open source version currently has some functions which are not available / incompatible. We are trying to resolve this soon.

**Comment by ogamimusashi** [comment]
Dear sir,
Thank you, So for the moment i can't help it? The 2.1 version doesn't have free licensing for some use (like mine which is academic,i'm a student)?

**Comment by pavanky** [comment]
@ogamimusashi We are working to fix this soon. It will take us a couple of weeks to fix the issue.

**Comment by ogamimusashi** [comment]
Thank you, i'm looking forward to it :)

**Comment by ogamimusashi** [comment]
Hello it's me again,

Forgot to ask: how to know when update is ready ? (do i need to check a special file or something like that?)

Thank you!

**Comment by pavanky** [comment]
@ogamimusashi I will close this issue when the update is ready. I am really sorry this is taking all this time.

--
Pavan

**Comment by ogamimusashi** [comment]
No problem:) i know how unpredictable development can be :)

Thank you
